openapi: 3.0.0
info:
  title: Hero service API
  description: Documentation Swagger pour l'API Hero service.
  version: 0.0.1
servers:
  - url: http://localhost:3002

paths:
  /heroes:
    get:
      summary: Get all heroes
      tags:
        - Heroes
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero:  
    post:
      summary: Create a new hero
      tags:
        - Hero
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hero'
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero/{id}:
    get:
      summary: Get a hero by id
      tags:
        - Hero
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero/{id}/healthPoints:
    put:
      summary: Update the health points of a hero
      tags:
        - Hero Stats
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                healthPoints:
                  type: integer
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero/{id}/healthPointsMax:
    put:
      summary: Update the maximum health points of a hero
      tags:
        - Hero Stats
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                healthPoints:
                  type: integer
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero/{id}/level:
    put:
      summary: Update the level of a hero
      tags:
        - Hero Stats
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: integer
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero/{id}/attackPoints:
    put:
      summary: Update the attack points of a hero
      tags:
        - Hero Stats
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                attackPoints:
                  type: integer
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
  /hero/{id}/inventory:
    put:
      summary: Update the inventory of a hero
      tags:
        - Hero Inventory
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inventory:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      quantity:
                        type: integer
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Hero'
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
    get:
      summary: Get a hero's inventory by id
      tags:
        - Hero Inventory
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
              '200':
                description: Ok
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          quantity:
                            type: integer
              '400':
                description: Bad Request
              '500':
                description: Internal Server Error
components:
  schemas:
    Hero:
      type: object
      required:
        - id
        - name
        - healthPoints
        - healthPointsMax
        - level
        - attackPoints
        - inventory
        - or
      properties:
        id:
          type: integer
        name:
          type: string
        healthPoints:
          type: integer
        healthPointsMax:
          type: integer
        level:
          type: integer
        attackPoints:
          type: integer
        inventory:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              quantity:
                type: integer
        or:
          type: integer
