openapi: 3.0.0
info:
  title: Mob service API
  description: Documentation Swagger pour l'API Mob service.
  version: 0.0.1
servers:
  - url: http://localhost:3006

paths:
  /mobs:
    get:
      summary: Get mobs
      tags:
        - Mobs
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mob'
        '500':
          description: Internal Server Error
  /mobs/{uuid}:
    get:
      summary: Get a mob by uuid
      tags:
        - Mobs
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  mob:
                    $ref: '#/components/schemas/Mob'
        '500':
          description: Internal Server Error
        '404':
          description: Not Found
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
  /mobs/type/{type}:
    get:
      summary: Get mobs by type
      tags:
        - Mobs
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum: ['Common', 'Boss']
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mob'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    
components:
  schemas:
    Mob:
      type: object
      required:
        - name
        - hp
        - attack
        - type
      properties:
        name:
          type: string
        hp:
          type: integer
        attack:
          type: integer
        type:
          type: string
          enum: ['Common', 'Boss']
